### PR TITLE
search_pypi_top.py: add some colour

### PR DESCRIPTION
**Pull request by hugovk**
Similar to https://github.com/vstinner/misc/pull/15.

Add some colour to `search_pypi_top.py` to improve readability. Use same colours as grep, magenta and bold red.

image

Doesn't cause any noticeable delay, here's the same search with `main`:

```console
$ python search_pypi_top.py out-2022-06-12 "\b(currentThread|activeCount|notifyAll|isSet|isDaemon|setDaemon)\b" -q
```

image

### CODE REVIEW

**Comment by vstinner** [comment]
I don't know termcolor. Is there a way to disable colors?

**Comment by hugovk** [comment]
Like for `download_pypi_top.py`, if termcolor is not installed colour is disabled.

If you like, I can also add either a switch (for example `--no-color` like pip or `--color=yes|no|auto` like pytest) and/or env var ([`NO_COLOR`](https://no-color.org/) like pytest)?

**Comment by vstinner** [comment]
> Like for download_pypi_top.py, if termcolor is not installed colour is disabled.

I only run download_pypi_top.py once a while, I don't care about its termcolor warning.

But for the search script, I run it often. I would prefer to not be annoyed by a warning, and so I will just install the dependency to make the warning quiet.

I'm more worried about redirections into a file, into a pipe, etc. I don't know if escape codes are generated or not in this case. It's not convenient to get escape codes in a file.

**Comment by hugovk** [comment]
Good point, it was also printing escape codes to the file, we don't want to do that.

I've updated it so colour is used for printing to terminal, and no colour for printing to the `--output` file.

**Comment by vstinner** [comment]
I didn't test it, I trust you :-D I merged your PR, thanks. At least, it seems useful to you.

**Pull request merged**
